# Introduction


## Bisection algorithm

1. Define an interval $[a, b]$ such that the result falls in the interval 
2. Divide into two subintervals $[a,(a+b)/2]$ and $[(a+b)/2,b]$
3. Choose the subinterval contaning the result and repeat 2 until error is less than a predefined threshold

In [1]:
my_sqrt = function(x, Error){
    a = 0
    if(x < 1){
        b = 1
    }else b = x

    middle = (a+b)/2
    error = abs(middle^2-x)

    nit = 0
    while(error > Error){
        nit = nit + 1
        middle = (a+b)/2
        if (middle^2 > x){
            b = middle 
        }else a = middle 

        error = abs(b-a)
    }
    
    result = list(value=as.numeric, error=as.numeric, nit=as.numeric)
    result$value = middle
    result$error = abs(middle^2-x)
    result$nit = nit
    result
}

my_sqrt(x=2, Error=10e-3)

$value
[1] 1.414062

$error
[1] 0.0004272461

$nit
[1] 8

## Newton-Raphson algorithm

The derivative of a differentiable function $f(x)$ at $x^*$ can be approximated by the ratio, i.e., 
$$f'(x^*) \approx \frac{f(x)-f(x^*)}{x-x^*}$$

which is equivalent to
$$x^* = x - \frac{f(x)-f(x^*)}{f'(x)}$$

This recursive equation can be used find a solution to an equation $f(x)=a$,  
$$x_{n+1} = x_{n} - \frac{f(x_n)-a}{f'(x_n)}$$

For example, define $f(x)=x^2$ and $\sqrt{2}$ is the solution to the equation $f(x)=2$. Thus, the recursive function is 
$$x_{n+1} = x_{n} - \frac{x_n^2-a}{2x_n}$$



In [2]:
my_sqrt1 = function(x, Error){  
    old = x/2
    error = Error+1
    nit = 0
    while(error > Error){
        nit = nit+1
        new = old - (old^2-x)/(2*old)
        error = abs(new-old)
        old = new
    }
    result = list(value=as.numeric, error=as.numeric, nit=as.numeric)
    result$value = new
    result$error = abs(new^2-x)
    result$nit = nit
    result  
}
my_sqrt1(2,Error=0.001)


$value
[1] 1.414214

$error
[1] 4.510614e-12

$nit
[1] 4

## Infinite sequences for calculating $\pi$ and $e$

In [3]:
n=10000
print((1+1/n)^n)

n=10000
x = 0
for(i in 1:n) x = x + (-1)^(i-1)/(2*i-1)
print(4*x)


[1] 2.718146
[1] 3.141493


## Numerical Integration

To calculate the integral $\int_a^bf(x)dx$, we divide the interval $[a,b]$ into smaller intervals $[a,a+\delta], [a+\delta,a+2\delta],\dot,[a+(n-1)\delta,b]$. Then $\int_a^bf(x)dx\approx \sum_{i=1}^nf(a+i\delta)\delta$.

In [4]:
n=100
a=0
b=1
delta = (b-a)/n

integral = 0
for(i in 1:n) integral = integral+(a+i*delta)^2 * delta

integral

[1] 0.33835

## Numerical Differentiation

$$f'(x)=lim_{\delta x\rightarrow 0}\frac{f(x+\delta x)-f(x)}{\delta x}$$

In [5]:
x=3
delta = 0.1

((x+delta)^2-x^2)/delta

[1] 6.1

# Chapter 1: Numerical Linear Algebra

## Gaussian Elimination and Backward Substitution

### 1. Gaussian Elimination

In [6]:
gaussElimination <- function (a) {
  n <- nrow (a)
  for (i in 1 : (n-1)) {
    a[i,] <- a[i,]/a[i,i]

    for (j in (i + 1) : n) {
      a[j,] <- a[j, ]/a[j,i] - a[i,]
    }
  }
  if(a[n,n] != 0) a[n,] = a[n,]/a[n,n]
    
  return (a)
}

set.seed(123456)
a <- matrix (runif(16), 4, 4)
a

fa = gaussElimination(a)
fa


[,1]      [,2]       [,3]      [,4]     
[1,] 0.7977843 0.36129411 0.9878469 0.9053100
[2,] 0.7535651 0.19834473 0.1675695 0.8808486
[3,] 0.3912557 0.53485796 0.7979891 0.9938366
[4,] 0.3415567 0.09652624 0.5937940 0.8959563

[,1] [,2]      [,3]     [,4]      
[1,] 1    0.4528719 1.238238  1.1347804
[2,] 0    1.0000000 5.356168 -0.1799404
[3,] 0    0.0000000 1.000000 -0.3833483
[4,] 0    0.0000000 0.000000  1.0000000

### 2. Backward Substitution

In [7]:
backwardSubstitution <- function (a) {
  n <- nrow (a)
    for (i in n : 2) {
        a[i,] = a[i,]/a[i,i]
        for (j in (i - 1) : 1) {
            a[j,] <- a[j,]/a[j,i] - a[i,]
        }
    }
    if(a[1,1] != 0) a[1,] = a[1,]/a[1,1]
    return (a)
}
backwardSubstitution(fa)


[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

### 3. Solving a system of linear equations

In [8]:
set.seed(123456)
y = 1:4
a = matrix(runif(16),4,4)
b = cbind(a,y)
b

y
[1,] 0.7977843 0.36129411 0.9878469 0.9053100 1
[2,] 0.7535651 0.19834473 0.1675695 0.8808486 2
[3,] 0.3912557 0.53485796 0.7979891 0.9938366 3
[4,] 0.3415567 0.09652624 0.5937940 0.8959563 4

In [9]:
fb = gaussElimination(b)
fb

y        
[1,] 1 0.4528719 1.238238  1.1347804  1.253472
[2,] 0 1.0000000 5.356168 -0.1799404 -7.384551
[3,] 0 0.0000000 1.000000 -0.3833483 -3.214798
[4,] 0 0.0000000 0.000000  1.0000000  6.873204

In [10]:
backwardSubstitution(fb)

y         
[1,] 1 0 0 0 -4.4506120
[2,] 0 1 0 0 -3.0413798
[3,] 0 0 1 0 -0.5799676
[4,] 0 0 0 1  6.8732039

### 4. Matrix inverse

In [11]:
set.seed(123456)
y = 1:4
a = matrix(runif(16),4,4)
b = cbind(a,diag(4))
b

[,1]      [,2]       [,3]      [,4]      [,5] [,6] [,7] [,8]
[1,] 0.7977843 0.36129411 0.9878469 0.9053100 1    0    0    0   
[2,] 0.7535651 0.19834473 0.1675695 0.8808486 0    1    0    0   
[3,] 0.3912557 0.53485796 0.7979891 0.9938366 0    0    1    0   
[4,] 0.3415567 0.09652624 0.5937940 0.8959563 0    0    0    1

In [12]:
fb = gaussElimination(b)
fb

[,1] [,2]      [,3]     [,4]       [,5]      [,6]       [,7]      
[1,] 1    0.4528719 1.238238  1.1347804  1.253472  0.0000000  0.0000000
[2,] 0    1.0000000 5.356168 -0.1799404  6.608927 -6.9967386  0.0000000
[3,] 0    0.0000000 1.000000 -0.3833483  1.781432 -1.5619114 -0.6241359
[4,] 0    0.0000000 0.000000  1.0000000 -1.322579  0.5074595  0.4409057
     [,8]    
[1,] 0.000000
[2,] 0.000000
[3,] 0.000000
[4,] 1.464537

In [13]:
result = backwardSubstitution(fb)
result

[,1] [,2] [,3] [,4] [,5]       [,6]       [,7]       [,8]      
[1,] 1    0    0    0     1.3823645  0.9277668 -1.0766737 -1.1146222
[2,] 0    1    0    0    -0.4550865  0.4184788  2.5170115 -2.7435713
[3,] 0    0    1    0     1.2744237 -1.3673777 -0.4551154  0.5614276
[4,] 0    0    0    1    -1.3225793  0.5074595  0.4409057  1.4645367

In [14]:
result[,5:8] %*% a

[,1]          [,2]          [,3]          [,4]         
[1,]  1.000000e+00  8.326673e-17  5.551115e-16  2.220446e-16
[2,] -1.110223e-16  1.000000e+00 -4.440892e-16  0.000000e+00
[3,] -1.665335e-16 -2.775558e-17  1.000000e+00 -3.330669e-16
[4,] -1.110223e-16  5.551115e-17 -1.110223e-16  1.000000e+00

## LU Decomposition

### Algorithm (from https://rdrr.io/cran/matrixcalc/src/R/lu.decomposition.R)

In [15]:
lu.decomposition <- function( x )
{
###
### This function performs an LU decomposition of the given square matrix argument
### the results are returned in a list of named components.  The Doolittle decomposition
### method is used to obtain the lower and upper triangular matrices
###
### arguments
### x = a square numeric matrix
###
    if ( nrow(x) != ncol(x) )
        stop( "argument x is not a square matrix" )
    if ( !is.numeric( x ) )
        stop( "argument x is not numeric" )
    n <- nrow( x )
    L <- matrix( 0, nrow=n, ncol=n )
    U <- matrix( 0, nrow=n, ncol=n )
    diag( L ) <- rep( 1, n )
    for ( i in 1:n ) {
        ip1 <- i + 1
        im1 <- i - 1
        for ( j in 1:n ) {
            U[i,j] <- x[i,j]
            if ( im1 > 0 ) {
                for ( k in 1:im1 ) {
                    U[i,j] <- U[i,j] - L[i,k] * U[k,j]
                }
            }
        }
        if ( ip1 <= n ) {
            for ( j in ip1:n ) {
                L[j,i] <- x[j,i]
                if ( im1 > 0 ) {
                    for ( k in 1:im1 ) {
                        L[j,i] <- L[j,i] - L[j,k] * U[k,i]
                    }
                }
                if ( U[i,i] == 0 )
                    stop( "argument x is a singular matrix" )
                L[j,i] <- L[j,i] / U[i,i]
            }    
        }
    }
    result <- list( L=L, U=U )
    return( result )
}

### Matrix LU Decomposition

In [16]:
set.seed(123456)
a = matrix(runif(16),4,4)
result = lu.decomposition(a)
result

$L
          [,1]       [,2]       [,3] [,4]
[1,] 1.0000000  0.0000000  0.0000000    0
[2,] 0.9445725  1.0000000  0.0000000    0
[3,] 0.4904279 -2.5025183  1.0000000    0
[4,] 0.4281316  0.4068967 -0.3010548    1

$U
          [,1]       [,2]       [,3]       [,4]
[1,] 0.7977843  0.3612941  0.9878469 0.90531001
[2,] 0.0000000 -0.1429237 -0.7655235 0.02571775
[3,] 0.0000000  0.0000000 -1.6022152 0.61420641
[4,] 0.0000000  0.0000000  0.0000000 0.68280978

### Using LU to find matrix inverse
1. Forward elimination

In [17]:
print("combine the lower triangular matrix with the identity matrix")
b = cbind(result$L,diag(4))
b

fb = gaussElimination(b)
print("forward elimination")
fb

[1] "combine the lower triangular matrix with the identity matrix"


[,1]      [,2]       [,3]       [,4] [,5] [,6] [,7] [,8]
[1,] 1.0000000  0.0000000  0.0000000 0    1    0    0    0   
[2,] 0.9445725  1.0000000  0.0000000 0    0    1    0    0   
[3,] 0.4904279 -2.5025183  1.0000000 0    0    0    1    0   
[4,] 0.4281316  0.4068967 -0.3010548 1    0    0    0    1

[1] "forward elimination"


[,1] [,2] [,3] [,4] [,5]       [,6]      [,7]      [,8]
[1,] 1    0    0    0     1.0000000 0.0000000 0.0000000 0   
[2,] 0    1    0    0    -0.9445725 1.0000000 0.0000000 0   
[3,] 0    0    1    0    -2.8542377 2.5025183 1.0000000 0   
[4,] 0    0    0    1    -0.9030700 0.3464983 0.3010548 1

2. Backward elimination

In [18]:
c = cbind(result$U, fb[,5:8])
c

print("backward substitution")
fc = backwardSubstitution(c)
fc

print("check if it is the inverse")
fc[,5:8] %*% a

[,1]      [,2]       [,3]       [,4]       [,5]       [,6]      [,7]     
[1,] 0.7977843  0.3612941  0.9878469 0.90531001  1.0000000 0.0000000 0.0000000
[2,] 0.0000000 -0.1429237 -0.7655235 0.02571775 -0.9445725 1.0000000 0.0000000
[3,] 0.0000000  0.0000000 -1.6022152 0.61420641 -2.8542377 2.5025183 1.0000000
[4,] 0.0000000  0.0000000  0.0000000 0.68280978 -0.9030700 0.3464983 0.3010548
     [,8]
[1,] 0   
[2,] 0   
[3,] 0   
[4,] 1

[1] "backward substitution"


[,1] [,2] [,3] [,4] [,5]       [,6]       [,7]       [,8]      
[1,] 1    0    0    0     1.3823645  0.9277668 -1.0766737 -1.1146222
[2,] 0    1    0    0    -0.4550865  0.4184788  2.5170115 -2.7435713
[3,] 0    0    1    0     1.2744237 -1.3673777 -0.4551154  0.5614276
[4,] 0    0    0    1    -1.3225793  0.5074595  0.4409057  1.4645367

[1] "check if it is the inverse"


[,1]          [,2]          [,3]          [,4]         
[1,]  1.000000e+00  0.000000e+00  2.220446e-16  4.440892e-16
[2,]  0.000000e+00  1.000000e+00  6.661338e-16  4.440892e-16
[3,] -8.326673e-17 -2.081668e-17  1.000000e+00 -2.220446e-16
[4,]  0.000000e+00  5.551115e-17 -1.110223e-16  1.000000e+00

## QR Decomposition
### R code

In [19]:
set.seed(123456)
a = matrix(runif(16),4,4)
a
result = qr(a)

print("Q matrix")
qr.Q(result)

print("R matrix")
qr.R(result)

print("check if the QR decomposition is correct")
qr.Q(result)%*%qr.R(result)

[,1]      [,2]       [,3]      [,4]     
[1,] 0.7977843 0.36129411 0.9878469 0.9053100
[2,] 0.7535651 0.19834473 0.1675695 0.8808486
[3,] 0.3912557 0.53485796 0.7979891 0.9938366
[4,] 0.3415567 0.09652624 0.5937940 0.8959563

[1] "Q matrix"


[,1]       [,2]        [,3]       [,4]      
[1,] -0.6570941 -0.01719891  0.4067462 -0.6344202
[2,] -0.6206730 -0.38328107 -0.6392239  0.2434203
[3,] -0.3222573  0.91007810 -0.1522424  0.2114955
[4,] -0.2813228 -0.15670891  0.6346436  0.7025149

[1] "R matrix"


[,1]     [,2]       [,3]       [,4]      
[1,] -1.21411 -0.5600284 -1.1773199 -1.7139169
[2,]  0.00000  0.3894003  0.5519635  0.4108816
[3,]  0.00000  0.0000000  0.5500484  0.2224808
[4,]  0.00000  0.0000000  0.0000000  0.4796841

[1] "check if the QR decomposition is correct"


[,1]      [,2]       [,3]      [,4]     
[1,] 0.7977843 0.36129411 0.9878469 0.9053100
[2,] 0.7535651 0.19834473 0.1675695 0.8808486
[3,] 0.3912557 0.53485796 0.7979891 0.9938366
[4,] 0.3415567 0.09652624 0.5937940 0.8959563

### QR Method for Finding Eigensystems

In [20]:
A=matrix(runif(16),4)
A=A+t(A)
print("A is a symmetric matrix")
A

A1=A
iter=0

while(sum(abs(lower.tri(A1)))>1e-6 & iter<10000){
  iter = iter+1
  result = qr(A1)
  Q=qr.Q(result)
  R=qr.R(result)
  A1=R%*%Q
}

print("The diagonal matrix is ")
A1

print("The eigenvalues of matrix A are ")
diag(A1)

[1] "A is a symmetric matrix"


[,1]      [,2]      [,3]      [,4]     
[1,] 1.7572867 0.3571993 0.8127714 1.6310859
[2,] 0.3571993 0.1612905 0.8331551 0.3378929
[3,] 0.8127714 0.8331551 1.7597781 1.4007624
[4,] 1.6310859 0.3378929 1.4007624 1.7382564

[1] "The diagonal matrix is "


[,1]     [,2]         [,3]          [,4]         
[1,] 4.511454 4.714409e-16  3.298782e-16  4.032537e-16
[2,] 0.000000 1.098270e+00  2.759813e-17 -1.101242e-16
[3,] 0.000000 0.000000e+00 -3.116594e-01  2.150840e-17
[4,] 0.000000 0.000000e+00  0.000000e+00  1.185478e-01

[1] "The eigenvalues of matrix A are "


[1]  4.5114535  1.0982698 -0.3116594  0.1185478